# Cloudflare Pages 配置文件
name = "nietest"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
NEXT_PUBLIC_USE_API_PROXY = "true"
NEXT_PUBLIC_API_BASE_URL = "https://nietesetbackend.talesofai.cn"

# 预览环境配置
[env.preview.vars]
NEXT_PUBLIC_USE_API_PROXY = "true"
NEXT_PUBLIC_API_BASE_URL = "https://nietesetbackend.talesofai.cn"

# 生产环境配置
[env.production.vars]
NEXT_PUBLIC_USE_API_PROXY = "true"
NEXT_PUBLIC_API_BASE_URL = "https://nietesetbackend.talesofai.cn"
